{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "854f4ca7",
   "metadata": {},
   "source": [
    "# Generate morphotope-level attributes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "fd26c364-f428-424d-ba6e-84a54335f77a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import geopandas as gpd\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from libpysal.graph import read_parquet, Graph\n",
    "from shapely import unary_union\n",
    "import momepy as mm\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "from shapely import get_coordinates\n",
    "from scipy.cluster.hierarchy import single\n",
    "from scipy.spatial.distance import pdist"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "81eb5820-b6a2-48a8-87be-92634068f2f1",
   "metadata": {},
   "outputs": [],
   "source": [
    "model_params = \"_post_processing_v1\"\n",
    "buildings_dir = \"/data/uscuni-ulce/processed_data/buildings/\"\n",
    "graph_dir = \"/data/uscuni-ulce/processed_data/neigh_graphs/\"\n",
    "morph_dir = \"/data/uscuni-ulce/processed_data/morphotopes/\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e66d1f98-1868-4dfb-bfd8-7d5887a2a3b5",
   "metadata": {},
   "outputs": [],
   "source": [
    "regions_datadir = \"/data/uscuni-ulce/\"\n",
    "region_hulls = gpd.read_parquet(\n",
    "    regions_datadir + \"regions/\" + \"cadastre_regions_hull.parquet\"\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "53df537f-c535-4b3b-8eb5-f3c3b86e2bc2",
   "metadata": {},
   "source": [
    "## Parallel processing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "bc2f59f1-ad61-4850-bb6b-ea660d046872",
   "metadata": {},
   "outputs": [],
   "source": [
    "def morphotopes_to_etcs(region_id, etcs=True, model_params=\"_100_0_None_None_False\"):\n",
    "    if etcs:\n",
    "        etcs = gpd.read_parquet(\n",
    "            f\"/data/uscuni-ulce/processed_data/tessellations/tessellation_{region_id}.parquet\"\n",
    "        )\n",
    "\n",
    "    else:\n",
    "        etcs = gpd.read_parquet(\n",
    "            f\"/data/uscuni-ulce/processed_data/buildings/buildings_{region_id}.parquet\"\n",
    "        )\n",
    "\n",
    "    etcs[\"label\"] = -1\n",
    "\n",
    "    morphotopes = pd.read_parquet(\n",
    "        f\"/data/uscuni-ulce/processed_data/morphotopes/tessellation_labels_morphotopes_{region_id}{model_params}.pq\"\n",
    "    )\n",
    "    morphotopes.loc[:, \"morphotope_label\"] = morphotopes.values[:, 0]\n",
    "\n",
    "    morph_dict = pd.Series(\n",
    "        np.arange(np.unique(morphotopes.values).shape[0]), np.unique(morphotopes.values)\n",
    "    )\n",
    "    etcs.loc[morphotopes.index, \"label\"] = morphotopes.map(\n",
    "        lambda x: morph_dict.loc[x]\n",
    "    ).values\n",
    "    etcs[\"morph\"] = str(region_id) + \"_\" + \"-1\"\n",
    "    etcs.loc[morphotopes.index, \"morph\"] = str(region_id) + \"_\" + morphotopes.values\n",
    "    return etcs\n",
    "\n",
    "\n",
    "def generate_ratio(group, buildings_q1):\n",
    "    group_graph = buildings_q1.subgraph(group.index)\n",
    "    connected_buildings = group.geometry.groupby(group_graph.component_labels).apply(\n",
    "        lambda x: unary_union(x.values)\n",
    "    )\n",
    "    libNCos = group.libNCo.median()\n",
    "    connected_buildings = connected_buildings\n",
    "\n",
    "    areas = connected_buildings.area\n",
    "    elongation = mm.elongation(connected_buildings)\n",
    "    fr = mm.facade_ratio(connected_buildings)\n",
    "    thin = (fr < 8) & (elongation < 0.90)\n",
    "\n",
    "    morph_fr_area_ratio = areas[thin].sum() / areas.sum()\n",
    "    morph_fr_count_ratio = (\n",
    "        connected_buildings[thin].count() / connected_buildings.count()\n",
    "    )\n",
    "\n",
    "    largest = areas > areas.median()\n",
    "    largest_thin = thin & largest\n",
    "\n",
    "    largest_morph_fr_area_ratio = areas[largest_thin].sum() / areas[largest].sum()\n",
    "\n",
    "    limLPS = ((morph_fr_area_ratio > 0.4) | (libNCos > 0)).astype(int)\n",
    "\n",
    "    ## add distances between buildings in the morphotope\n",
    "\n",
    "    if connected_buildings.shape[0] > 3:\n",
    "        tri = Graph.build_triangulation(\n",
    "            connected_buildings.representative_point(),\n",
    "            method=\"relative_neighborhood\",\n",
    "            kernel=\"identity\",\n",
    "        )\n",
    "        val = tri._adjacency.describe()[\"std\"] / connected_buildings.length.median()\n",
    "    elif group.shape[0] < 3:\n",
    "        # 99886 has a isolated building that gets treated as a morphotope\n",
    "        val = 0.35\n",
    "    else:\n",
    "        tri = Graph.build_triangulation(\n",
    "            group.representative_point(),\n",
    "            method=\"relative_neighborhood\",\n",
    "            kernel=\"identity\",\n",
    "        )\n",
    "        val = tri._adjacency.describe()[\"std\"] / connected_buildings.length.median()\n",
    "\n",
    "    limit_value = 10\n",
    "\n",
    "    return pd.Series(\n",
    "        {\n",
    "            \"limMFR\": morph_fr_area_ratio,\n",
    "            \"limMTC\": morph_fr_count_ratio,\n",
    "            \"limLMFR\": largest_morph_fr_area_ratio,\n",
    "            \"limLPS\": limLPS,\n",
    "            \"limAre\": connected_buildings.geometry.area.sort_values(ascending=True)[\n",
    "                -min(limit_value, connected_buildings.shape[0]) :\n",
    "            ].sum(),\n",
    "            \"limPer\": connected_buildings.geometry.length.sort_values(ascending=True)[\n",
    "                -min(limit_value, connected_buildings.shape[0]) :\n",
    "            ].sum(),\n",
    "            \"limLAL\": mm.longest_axis_length(connected_buildings)\n",
    "            .sort_values(ascending=True)[\n",
    "                -min(limit_value, connected_buildings.shape[0]) :\n",
    "            ]\n",
    "            .sum(),\n",
    "            \"limSDi\": val,\n",
    "        }\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "9df5c350-8e6d-4211-9c50-a7fe0c78b750",
   "metadata": {},
   "outputs": [],
   "source": [
    "def add_morph_chars(region_id):\n",
    "    etcs = morphotopes_to_etcs(region_id, model_params=model_params)\n",
    "    buildings = gpd.read_parquet(\n",
    "        f\"/data/uscuni-ulce/processed_data/chars/buildings_chars_{region_id}.parquet\"\n",
    "    )\n",
    "\n",
    "    morphs = etcs[etcs.morph.str.split(\"_\").str[-1] != \"-1\"].to_crs(epsg=3035)\n",
    "    buildings = buildings.loc[morphs.index]\n",
    "    buildings[\"morph\"] = etcs[\"morph\"]\n",
    "    buildings_q1 = read_parquet(graph_dir + f\"building_graph_{region_id}.parquet\")\n",
    "    res = buildings.groupby(\"morph\").apply(generate_ratio, buildings_q1)\n",
    "\n",
    "    res.to_parquet(\n",
    "        f\"/data/uscuni-ulce/processed_data/morphotopes/morph_chars_{region_id}.pq\"\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "e4e6af44-9546-456c-b5b7-f232403cd482",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_1096219/3526448083.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n",
      "/tmp/ipykernel_1096219/3526448083.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n",
      "/tmp/ipykernel_1096219/3526448083.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n",
      "/tmp/ipykernel_1096219/3526448083.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/3526448083.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n",
      "/tmp/ipykernel_1096219/3526448083.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n",
      "/tmp/ipykernel_1096219/3526448083.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n",
      "/tmp/ipykernel_1096219/3526448083.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/285831131.py:41: RuntimeWarning: invalid value encountered in scalar divide\n",
      "/tmp/ipykernel_1096219/3526448083.py:10: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 1.88 s, sys: 1.05 s, total: 2.93 s\n",
      "Wall time: 14min 4s\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "from joblib import Parallel, delayed\n",
    "\n",
    "n_jobs = -1\n",
    "new = Parallel(n_jobs=n_jobs)(\n",
    "    delayed(add_morph_chars)(region_id) for region_id, _ in region_hulls.iterrows()\n",
    ")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
